//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.02 at 07:21:58 PM SAMT 
//


package dbwork.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * —ведени€ об адресе
 * 
 * <p>Java class for јдрес“ип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="јдрес“ип">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="јдр–‘" type="{}јдр–‘“ип"/>
 *         &lt;element name="јдр»но" type="{}јдр»но“ип"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "јдрес“ип", propOrder = {
    "адр–‘",
    "адр»но"
})
public class јдрес“ип {

    @XmlElement(name = "јдр–‘")
    protected јдр–‘“ип адр–‘;
    @XmlElement(name = "јдр»но")
    protected јдр»но“ип адр»но;

    /**
     * Gets the value of the адр–‘ property.
     * 
     * @return
     *     possible object is
     *     {@link јдр–‘“ип }
     *     
     */
    public јдр–‘“ип getјдр–‘() {
        return адр–‘;
    }

    /**
     * Sets the value of the адр–‘ property.
     * 
     * @param value
     *     allowed object is
     *     {@link јдр–‘“ип }
     *     
     */
    public void setјдр–‘(јдр–‘“ип value) {
        this.адр–‘ = value;
    }

    /**
     * Gets the value of the адр»но property.
     * 
     * @return
     *     possible object is
     *     {@link јдр»но“ип }
     *     
     */
    public јдр»но“ип getјдр»но() {
        return адр»но;
    }

    /**
     * Sets the value of the адр»но property.
     * 
     * @param value
     *     allowed object is
     *     {@link јдр»но“ип }
     *     
     */
    public void setјдр»но(јдр»но“ип value) {
        this.адр»но = value;
    }

}
