//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.02 at 07:21:58 PM SAMT 
//


package dbwork.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * јдрес за пределами –оссийской ‘едерации
 * 
 * <p>Java class for јдр»но“ип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="јдр»но“ип">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name=" од—тр" use="required" type="{}ќ —ћ“ип" />
 *       &lt;attribute name="јдр“екст" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="255"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "јдр»но“ип")
public class јдр»но“ип {

    @XmlAttribute(name = " од—тр", required = true)
    protected String код—тр;
    @XmlAttribute(name = "јдр“екст", required = true)
    protected String адр“екст;

    /**
     * Gets the value of the код—тр property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String get од—тр() {
        return код—тр;
    }

    /**
     * Sets the value of the код—тр property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void set од—тр(String value) {
        this.код—тр = value;
    }

    /**
     * Gets the value of the адр“екст property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getјдр“екст() {
        return адр“екст;
    }

    /**
     * Sets the value of the адр“екст property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setјдр“екст(String value) {
        this.адр“екст = value;
    }

}
