//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.02 at 07:21:58 PM SAMT 
//


package dbwork.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * —ведени€ о грузоотправителе (грузополучателе)
 * 
 * <p>Java class for —в√рузќтпрѕол“ип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="—в√рузќтпрѕол“ип">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ќаим√ќѕ">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Ќаимќрг">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="1000"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="‘»ќ»ѕ" type="{}‘»ќ“ип"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="јдрес" type="{}јдрес“ип"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "—в√рузќтпрѕол“ип", propOrder = {
    "наим√ќѕ",
    "адрес"
})
public class —в√рузќтпрѕол“ип {

    @XmlElement(name = "Ќаим√ќѕ", required = true)
    protected —в√рузќтпрѕол“ип.Ќаим√ќѕ наим√ќѕ;
    @XmlElement(name = "јдрес", required = true)
    protected јдрес“ип адрес;

    /**
     * Gets the value of the наим√ќѕ property.
     *
     * @return
     *     possible object is
     *     {@link —в√рузќтпрѕол“ип.Ќаим√ќѕ }
     *
     */
    public —в√рузќтпрѕол“ип.Ќаим√ќѕ getЌаим√ќѕ() {
        return наим√ќѕ;
    }

    /**
     * Sets the value of the наим√ќѕ property.
     *
     * @param value
     *     allowed object is
     *     {@link —в√рузќтпрѕол“ип.Ќаим√ќѕ }
     *
     */
    public void setЌаим√ќѕ(—в√рузќтпрѕол“ип.Ќаим√ќѕ value) {
        this.наим√ќѕ = value;
    }

    /**
     * Gets the value of the адрес property.
     *
     * @return
     *     possible object is
     *     {@link јдрес“ип }
     *
     */
    public јдрес“ип getјдрес() {
        return адрес;
    }

    /**
     * Sets the value of the адрес property.
     *
     * @param value
     *     allowed object is
     *     {@link јдрес“ип }
     *
     */
    public void setјдрес(јдрес“ип value) {
        this.адрес = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Ќаимќрг">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="1000"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="‘»ќ»ѕ" type="{}‘»ќ“ип"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "наимќрг",
        "фиоип"
    })
    public static class Ќаим√ќѕ {

        @XmlElement(name = "Ќаимќрг")
        protected String наимќрг;
        @XmlElement(name = "‘»ќ»ѕ")
        protected ‘»ќ“ип фиоип;

        /**
         * Gets the value of the наимќрг property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getЌаимќрг() {
            return наимќрг;
        }

        /**
         * Sets the value of the наимќрг property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setЌаимќрг(String value) {
            this.наимќрг = value;
        }

        /**
         * Gets the value of the фиоип property.
         * 
         * @return
         *     possible object is
         *     {@link ‘»ќ“ип }
         *     
         */
        public ‘»ќ“ип get‘»ќ»ѕ() {
            return фиоип;
        }

        /**
         * Sets the value of the фиоип property.
         * 
         * @param value
         *     allowed object is
         *     {@link ‘»ќ“ип }
         *     
         */
        public void set‘»ќ»ѕ(‘»ќ“ип value) {
            this.фиоип = value;
        }

    }

}
