//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.02 at 07:21:58 PM SAMT 
//


package dbwork.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * —ведени€ о продавце (покупателе)
 * 
 * <p>Java class for —вѕродѕок“ип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="—вѕродѕок“ип">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="»д—в">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="—вёЋ">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="Ќаимќрг" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="1"/>
 *                                 &lt;maxLength value="1000"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="»ЌЌёЋ" type="{}»ЌЌёЋ“ип" />
 *                           &lt;attribute name=" ѕѕ" type="{} ѕѕ“ип" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="—в‘Ћ">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="‘»ќ»ѕ" type="{}‘»ќ“ип"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="»ЌЌ‘Ћ" type="{}»ЌЌ‘Ћ“ип" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="јдрес" type="{}јдрес“ип"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "—вѕродѕок“ип", propOrder = {
    "ид—в",
    "адрес"
})
public class —вѕродѕок“ип {

    @XmlElement(name = "»д—в", required = true)
    protected —вѕродѕок“ип.»д—в ид—в;
    @XmlElement(name = "јдрес", required = true)
    protected јдрес“ип адрес;

    /**
     * Gets the value of the ид—в property.
     *
     * @return
     *     possible object is
     *     {@link —вѕродѕок“ип.»д—в }
     *
     */
    public —вѕродѕок“ип.»д—в get»д—в() {
        return ид—в;
    }

    /**
     * Sets the value of the ид—в property.
     *
     * @param value
     *     allowed object is
     *     {@link —вѕродѕок“ип.»д—в }
     *
     */
    public void set»д—в(—вѕродѕок“ип.»д—в value) {
        this.ид—в = value;
    }

    /**
     * Gets the value of the адрес property.
     *
     * @return
     *     possible object is
     *     {@link јдрес“ип }
     *
     */
    public јдрес“ип getјдрес() {
        return адрес;
    }

    /**
     * Sets the value of the адрес property.
     *
     * @param value
     *     allowed object is
     *     {@link јдрес“ип }
     *
     */
    public void setјдрес(јдрес“ип value) {
        this.адрес = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="—вёЋ">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="Ќаимќрг" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="1"/>
     *                       &lt;maxLength value="1000"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="»ЌЌёЋ" type="{}»ЌЌёЋ“ип" />
     *                 &lt;attribute name=" ѕѕ" type="{} ѕѕ“ип" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="—в‘Ћ">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="‘»ќ»ѕ" type="{}‘»ќ“ип"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="»ЌЌ‘Ћ" type="{}»ЌЌ‘Ћ“ип" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "свёЋ",
        "св‘Ћ"
    })
    public static class »д—в {

        @XmlElement(name = "—вёЋ")
        protected —вѕродѕок“ип.»д—в.—вёЋ свёЋ;
        @XmlElement(name = "—в‘Ћ")
        protected —вѕродѕок“ип.»д—в.—в‘Ћ св‘Ћ;

        /**
         * Gets the value of the свёЋ property.
         *
         * @return
         *     possible object is
         *     {@link —вѕродѕок“ип.»д—в.—вёЋ }
         *
         */
        public —вѕродѕок“ип.»д—в.—вёЋ get—вёЋ() {
            return свёЋ;
        }

        /**
         * Sets the value of the свёЋ property.
         *
         * @param value
         *     allowed object is
         *     {@link —вѕродѕок“ип.»д—в.—вёЋ }
         *
         */
        public void set—вёЋ(—вѕродѕок“ип.»д—в.—вёЋ value) {
            this.свёЋ = value;
        }

        /**
         * Gets the value of the св‘Ћ property.
         *
         * @return
         *     possible object is
         *     {@link —вѕродѕок“ип.»д—в.—в‘Ћ }
         *
         */
        public —вѕродѕок“ип.»д—в.—в‘Ћ get—в‘Ћ() {
            return св‘Ћ;
        }

        /**
         * Sets the value of the св‘Ћ property.
         *
         * @param value
         *     allowed object is
         *     {@link —вѕродѕок“ип.»д—в.—в‘Ћ }
         *
         */
        public void set—в‘Ћ(—вѕродѕок“ип.»д—в.—в‘Ћ value) {
            this.св‘Ћ = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="‘»ќ»ѕ" type="{}‘»ќ“ип"/>
         *       &lt;/sequence>
         *       &lt;attribute name="»ЌЌ‘Ћ" type="{}»ЌЌ‘Ћ“ип" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "фиоип"
        })
        public static class —в‘Ћ {

            @XmlElement(name = "‘»ќ»ѕ", required = true)
            protected ‘»ќ“ип фиоип;
            @XmlAttribute(name = "»ЌЌ‘Ћ")
            protected String иннфл;

            /**
             * Gets the value of the фиоип property.
             *
             * @return
             *     possible object is
             *     {@link ‘»ќ“ип }
             *
             */
            public ‘»ќ“ип get‘»ќ»ѕ() {
                return фиоип;
            }

            /**
             * Sets the value of the фиоип property.
             *
             * @param value
             *     allowed object is
             *     {@link ‘»ќ“ип }
             *
             */
            public void set‘»ќ»ѕ(‘»ќ“ип value) {
                this.фиоип = value;
            }

            /**
             * Gets the value of the иннфл property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String get»ЌЌ‘Ћ() {
                return иннфл;
            }

            /**
             * Sets the value of the иннфл property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void set»ЌЌ‘Ћ(String value) {
                this.иннфл = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="Ќаимќрг" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="1"/>
         *             &lt;maxLength value="1000"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="»ЌЌёЋ" type="{}»ЌЌёЋ“ип" />
         *       &lt;attribute name=" ѕѕ" type="{} ѕѕ“ип" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class —вёЋ {

            @XmlAttribute(name = "Ќаимќрг", required = true)
            protected String наимќрг;
            @XmlAttribute(name = "»ЌЌёЋ")
            protected String иннюл;
            @XmlAttribute(name = " ѕѕ")
            protected String кпп;

            /**
             * Gets the value of the наимќрг property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getЌаимќрг() {
                return наимќрг;
            }

            /**
             * Sets the value of the наимќрг property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setЌаимќрг(String value) {
                this.наимќрг = value;
            }

            /**
             * Gets the value of the иннюл property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String get»ЌЌёЋ() {
                return иннюл;
            }

            /**
             * Sets the value of the иннюл property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void set»ЌЌёЋ(String value) {
                this.иннюл = value;
            }

            /**
             * Gets the value of the кпп property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String get ѕѕ() {
                return кпп;
            }

            /**
             * Sets the value of the кпп property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void set ѕѕ(String value) {
                this.кпп = value;
            }

        }

    }

}
