//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.02 at 07:21:58 PM SAMT 
//


package dbwork.entity;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Ñóììà ÍÄÑ
 * 
 * <p>Java class for ÑóìÍÄÑÒèï complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ÑóìÍÄÑÒèï">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ÑóìÍÄÑ">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="19"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ÁåçÍÄÑ">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="7"/>
 *               &lt;enumeration value="áåç ÍÄÑ"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ÑóìÍÄÑÒèï", propOrder = {
    "ñóìÍÄÑ",
    "áåçÍÄÑ"
})
public class ÑóìÍÄÑÒèï {

    @XmlElement(name = "ÑóìÍÄÑ")
    protected BigDecimal ñóìÍÄÑ;
    @XmlElement(name = "ÁåçÍÄÑ")
    protected String áåçÍÄÑ;

    /**
     * Gets the value of the ñóìÍÄÑ property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getÑóìÍÄÑ() {
        return ñóìÍÄÑ;
    }

    /**
     * Sets the value of the ñóìÍÄÑ property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setÑóìÍÄÑ(BigDecimal value) {
        this.ñóìÍÄÑ = value;
    }

    /**
     * Gets the value of the áåçÍÄÑ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getÁåçÍÄÑ() {
        return áåçÍÄÑ;
    }

    /**
     * Sets the value of the áåçÍÄÑ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setÁåçÍÄÑ(String value) {
        this.áåçÍÄÑ = value;
    }

}
